# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmdGenie < Formula
  desc "CLI app to suggest prompted commands"
  homepage "https://github.com/the-Jinxist/cmd_genie"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.0/cmd_genie_Darwin_x86_64.tar.gz"
      sha256 "f09e711e588440230dfbab04d55c370ad15359c6a8d0ef850d8fe750308868bf"

      def install
        bin.install "cmd_genie"
      end
    end
    on_arm do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.0/cmd_genie_Darwin_arm64.tar.gz"
      sha256 "cd7783267e9e364869ec9010009b2f6679535eb3d210e355e6775047387cde01"

      def install
        bin.install "cmd_genie"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.0/cmd_genie_Linux_x86_64.tar.gz"
        sha256 "52ea51c6ea3018af406b50260789150eff294ada52fabea66f27d60d797d5f83"

        def install
          bin.install "cmd_genie"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.0/cmd_genie_Linux_arm64.tar.gz"
        sha256 "e6b9ea7bc82e933539b35732b0808ff1ad5ad9c93494dd4c4b73bbb095531a47"

        def install
          bin.install "cmd_genie"
        end
      end
    end
  end
end
